### ISSUE TITLE
Dependencies Not found

### ISSUE THREAD

**Issue by cloudhu** [peeweek/HDSimpleGame#1]
"net.peeweek.build-frontend": "file:D:/Unity/net.peeweek.build-frontend",
    "net.peeweek.console": "file:D:/Unity/net.peeweek.console",
    "net.peeweek.gameplay-ingredients": "file:D:/Unity/net.peeweek.gameplay-ingredients",
    "net.peeweek.third-person-controller": "file:D:/Unity/net.peeweek.third-person-controller",

**Comment by cloudhu** [comment]
Copy them from SpaceshipDemo and edit package.json as:
    "net.peeweek.build-frontend": "file:../LocalPackages/net.peeweek.build-frontend",
    "net.peeweek.console": "file:../LocalPackages/net.peeweek.console",
    "net.peeweek.gameplay-ingredients": "file:../LocalPackages/net.peeweek.gameplay-ingredients",
Also need to download net.peeweek.third-person-controller and config json.

**Comment by cloudhu** [comment]
Assets\Script\ConsoleCommnands\LoadLevelConsoleCommand.cs(9,44): error CS0246: The type or namespace name 'IConsoleCommand' could not be found (are you missing a using directive or an assembly reference?)
Assets\Script\ConsoleCommnands\LoadLevelConsoleCommand.cs(8,6): error CS0246: The type or namespace name 'AutoRegisterConsoleCommandAttribute' could not be found (are you missing a using directive or an assembly reference?)
Assets\Script\ConsoleCommnands\LoadLevelConsoleCommand.cs(8,6): error CS0246: The type or namespace name 'AutoRegisterConsoleCommand' could not be found (are you missing a using directive or an assembly reference?)
Assets\Script\ConsoleCommnands\LoadLevelConsoleCommand.cs(17,36): error CS0234: The type or namespace name 'Alias' does not exist in the namespace 'Console' (are you missing an assembly reference?)

**Comment by cloudhu** [comment]
Hey,man.We must have different version of references!

**Comment by peeweek** [comment]
Sorry about the mess, I totally changed the way to reference the packages recently, now, these are located directly under Packages/ folder making them visible as Development packages. The previous workflow was a bit hectic and the references you got in that version were totally broken.

**Comment by peeweek** [comment]
Sorry about the mess, I totally changed the way to reference the packages recently, now, these are located directly under LocalPackages/ folder (not referencing the git tags anymore). The previous workflow was a bit hectic because I did switch a lot between local references and git references. Now it's more convenient and should be more robust.
